<?php

/**
 * @file
 * OS2Web Banner module file.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function os2web_banner_theme() {
  return [
    'os2web_banner' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function os2web_banner_theme_suggestions_os2web_banner(array $variables) {
  $suggestions = [];
  $banner = $variables['elements']['#os2web_banner'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');
  $suggestions[] = 'os2web_banner__' . $sanitized_view_mode;
  $suggestions[] = 'os2web_banner__' . $banner->id();
  $suggestions[] = 'os2web_banner__' . $banner->id() . '__' . $sanitized_view_mode;

  return $suggestions;
}

/**
 * Prepares variables for OS2Web Banner templates.
 *
 * Default template: os2web_banner.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the user information and any
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_os2web_banner(array &$variables) {
  // Fetch Banner Entity Object.
  $os2web_banner = $variables['elements']['#os2web_banner'];
  $variables['banner'] = $os2web_banner;
  // Helpful $content variable for templates.
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
